### ISSUE TITLE
On debian 7.8 it fails to install

### ISSUE THREAD

**Issue by riemers** [geerlingguy/ansible-role-nodejs#3]
Added the role, ran it, came back with this:

```
TASK: [geerlingguy.nodejs | Add NodeSource PPA for latest version of Node.js.] ***
failed: [app-01] => {"failed": true}
msg: Invalid repository string: ppa:chris-lea/node.js
```

Docs on ansible says debian does not like "ppa" repo's.

p.s. used ubuntu now, since it seems the majority of ansible prefers that.

**Comment by VEBERArnaud** [comment]
Same problem here with debian 8

Do you plan to fix this issue ?

**Comment by verschoof** [comment]
ping @geerlingguy

**Comment by geerlingguy** [comment]
Is this still broken? The role has changed a bit in 2.0.0 and should work better across Debian releases.

**Comment by map7** [comment]
Still not working on Debian 8.3 I get the following error

```
TASK: [geerlingguy.nodejs | Ensure Node.js and npm are installed.] ************ 
failed: [192.168.200.215] => {"failed": true, "parsed": false}
BECOME-SUCCESS-bgmzuxslkujtgwbhbvgmtodmfdrtwyhy
Traceback (most recent call last):
  File "/home/map7/.ansible/tmp/ansible-tmp-1456359292.87-216422506613055/apt", line 2085, in <module>
    main()
  File "/home/map7/.ansible/tmp/ansible-tmp-1456359292.87-216422506613055/apt", line 437, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 443, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch https://deb.nodesource.com/node_4.3.1/dists/jessie/main/source/Sources  HttpError404
, W:Failed to fetch https://deb.nodesource.com/node_4.3.1/dists/jessie/main/binary-amd64/Packages  HttpError404
, E:Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by map7** [comment]
Still not working on Debian, I get the same error on Debian 8.3

**Comment by geerlingguy** [comment]
This issue is outdated, closing—tests are passing okay on Debian 8 and 9 anyways :)
